company_names = ['MRS CORO- Alaka',
 'MRS RORO - Oke Aro',
 'MRS COCO - Samaru',
 'MRS CORO - Festac',
 'MRS CORO - Unity Road',
 'MRS CORO - Ekpoma',
 'MRS CORO - Oke Afa',
 'MRS CORO - Asokoro',
 'Cormart Nigeria Limited',
 'Friesland Campina Wamco Nigeria PLC',
 'Flour mills of Nigeria PLC',
 'Atlantic Shrimpers',
 'UNITED STATES EMBASSY',
 'AZIKEL DREDGING NIG. LTD',
 'Access Bank Plc',
 'Bedrubo Group (Chuba Nig Ventures)',
 'MRS Agege',
 'MRS COCO - Lawanson',
 'MRS CORO - Airport Road',
 'MRS CORO - Ebute Metta',
 'MRS RORO - Apomu',
 'MRS Aba Road PH',
 'MRS CORO - Ondo Ore Road',
 'Bestaf Marine Services Limited',
 'MRS CORO - Mission Road',
 'MRS RORO - Link-Bridge Road',
 'MRS COCO - Rumuomasi',
 'MRS RORO - Amuwo Odofin',
 'MRS CORO - Ikoku Junction',
 'MRS COCO - CityWay',
 'MRS CORO - Alapere',
 'MRS CORO - Sabo',
 'MRS CORO - Lekki',
 'MRS Garrison Junction',
 'MRS CORO - Ishaga',
 'MRS COCO - Victoria Island',
 'African Reinsurance Corporation',
 'BERGER PAINTS',
 'MRS CORO - Ojota',
 'MRS RORO - Obiaruku',
 'MRS CORO - Akoka',
 'MRS CORO - New Haven',
 'MRS RORO-Abraka',
 'MRS RORO Ikate Lekki',
 'MRS CORO - Isale Igbeyin',
 'MRS RORO- Obudu',
 'MRS RORO - Keffi Abuja Road',
 'MRS RORO - Abeokuta Road',
 'MRS CORO - Uwani',
 'MRS RORO -Omularan',
 'MRS CORO - Jos Road',
 'MRS CORO - Kodesoh',
 'R. N. Iwobi',
 'MRS RORO -Zuba',
 'MRS RORO - Kastina-Ala Road',
 'MRS CORO - Obantoko',
 'MRS CORO - Ekewan Road',
 'MRS RORO - Ojoo',
 'MRS RORO - Gwantu',
 'MRS RORO- Oron',
 'CROWN FLOUR MILLS',
 'RED STAR EXPRESS PLC',
 'MRS RORO - Tella',
 'MRS CORO - Imo Street',
 'African Circle Pollution Management Company',
 'MRS RORO - Danzala',
 'MRS RORO - Akampka',
 'Hamisu Dantinki Motors',
 'MRS CORO - Sapele',
 'MRS RORO - Yandev-Gboko Road',
 'ONUORAH JOSEPHINE MRS',
 'CHINOCHUKS AUTO LTD',
 'ONYEFEE ZEE NIG LTD.',
 'MRS CORO - Kingsway Road',
 'MRS CORO - Emene',
 'MRS CORO - Ughelli',
 'MRS CORO - Sapele Road',
 'MRS CORO - Ali Akilu Road',
 'MRS RORO - Baissa',
 'MRS CORO - Mando Road',
 'MRS CORO - Uselu Lagos Road',
 'S.C Dubinson Nig. Ltd',
 'MRS Ahmadu Bello Way',
 'MRS RORO- Olunlade',
 'MRS COCO- Okpara Avenue',
 'ADOLF HYMAN NIG LTD',
 'Ola-Obi Tradings Stores',
 'MRS COCO - Oyo ByePass',
 'Hello Products Limited',
 'MRS RORO - Woji',
 "MRS COCO - Emir's Market",
 'MRS RORO - Bali',
 'MRS RORO -MRS Mubi Road, Michika',
 'MRS RORO -Hamma Ruwa Way',
 'MRS COCO - Brazillian Quarters',
 'MRS RORO - Ejirin Road',
 'MRS RORO - Ajah',
 'MRS RORO - Dadi Goma',
 'MRS CORO - Makola',
 'MRS CORO - Palmgrove',
 'MRS CORO - Tudun Wada',
 'MRS Adogo',
 'MRS CORO - Asa Road',
 'MRS RORO - Isale oko',
 'MRS CORO - Deco Road',
 'MRS COCO - Akanran',
 'MRS COCO- Igbosere',
 'MRS RORO - Mubi- Gella Road',
 'MRS RORO -Barracks Road',
 'MRS RORO-Old Ife Road',
 'MRS CORO - Warri/Sapele Road',
 'MRS CORO - Adekunle',
 'MRS COCO - Ikpoba Slope',
 'Osayomwanbor Nig Enterprise',
 'MRS RORO - Ikire',
 'MRS Wharf Road',
 'OSIKHENA COMPANY NIG LTD',
 'PURECHEM INDUSTRIES LTD',
 'MRS Itamope',
 'MRS RORO -Ajase Town',
 'MRS RORO -Toll Gate',
 'De Tastee Fried Chicken Ltd',
 'VITA FOAM - ABA',
 'MRS RORO - Kware',
 'MRS RORO -Gaya Road',
 'Air Peace',
 'Max Air',
 'MRS RORO - Azare',
 'MRS RORO-Gbogan-Osogbo Road',
 'Azman Air Services Limited',
 'MRS CORO - Oke Ado',
 'United Aviation  Services',
 'Gyro',
 'MRS COCO - Terminus',
 'MRS CORO - Okigwe',
 'MRS CORO - Challenge',
 'Bappa Hassan',
 'Clegee Nigeria LTD',
 'MRS RORO - Iwo Osogbo',
 'MRS RORO - Nguru Road, Gashua',
 'MRS CORO - Ibarra',
 'MRS RORO - Kaduna Abuja Expressway',
 'AD OIL COMPANY LTD',
 'Ethiopian Airlines',
 'MRS COCO - Onipetesi',
 'MRS CORO - Bodija Market',
 'MRS RORO - BenKalio Estate - Damaturu',
 'Associated Energy Group - USD',
 'Execujet',
 'MRS Holdings',
 'MRS RORO - Ijoko',
 'MRS Amawbia',
 'Aero Contractors Ltd',
 'MRS Along Ahmadu Bello, Gusau',
 'MRS CORO - Jubilee Junction',
 'MRS CORO - Bennard Carr Street',
 'MRS Sango',
 'MRS COCO - Agbani',
 'MRS COCO - MainStreet',
 'MRS CORO - Ikwerre Road Mile 3',
 'MRS CORO - Abakaliki',
 'MRS RORO - Nguru Road - Gashua',
 'DIVINE MERCY LOGISTICS',
 'MOHAMMED RAWA GANA',
 'MRS RORO - Muda Lawal Market',
 "MRS Jama're Road, Kiyawa",
 'Emirates Airline',
 'MRS CORO - Tamburawa',
 'MRS RORO -Bye-Pass, Birnin Kebbi',
 'MRS CORO - Warri Sapele Road',
 'MRS COCO - Bwari',
 'MRS CORO - Rumuogba',
 'MRS RORO - Ogijo Town',
 'MRS RORO -Igando Oloja',
 'Universal  Weather And Aviation',
 'MRS CORO - Amaigbo Road',
 'GOGO ALLIED IMPEX AND SERVICES LIMITED Station 1',
 'CHUCHORL NIGERIA LIMITED',
 'MRS CORO - Okesa',
 'MRS CORO - Katampe',
 'Woopet lubes shop',
 'MRS Gwoza 1',
 'MRS Umusadege Road',
 'MRS CORO - Effurun',
 'ASKY AIRLINES',
 'MRS Port Harcourt Road, Aba',
 'Jetex Fuel',
 'Turkish Airlines',
 'MRS CORO - Caretaker Road',
 'MRS RORO - Katsina-Unguwar',
 'MRS CORO - Igbosere',
 'NOBIS &ASSOCIATES NIG',
 'Cooperative',
 'NOTORE CHEMICAL IND. LTD',
 'NIGERIAN ENGINEERING WORKS LTD',
 'INDORAMA ELEME PETROCHEMICALS LTD',
 'MRS RORO - Yelwa-Yauri',
 'MRS COCO - Naka Road',
 'RwandAir',
 'Kenya Airways',
 'Premium Steel & Mines Ltd',
 'Nasco Foods Nigeria Limited',
 'Kano Sundry',
 'Deltex Haulage Co. Ltd',
 'Ikoyi club',
 'VITA FOAM - LAGOS',
 'GUINNESS NIGERIA LTD.',
 'NEST OIL_ WARRI',
 'Pacific Energy Co. Ltd.',
 'Joint Aviation Facility (JAF) Kano',
 'Triacta Nigeria Limited',
 'DEVYANI INTERNATIONAL NIGERIA LIMITED',
 'SMACKERS LIMITED',
 'UAC RESTAURANTS LTD',
 'Four Point by Sheraton',
 'TUNMORE NIGERIA LIMITED',
 'MRS RORO - Bama Road, Michika',
 'ABC Transport Plc, Lagos',
 'PZ Cussons Nigeria PLC',
 'ADLER (ACVS) limited',
 'Lily Gate Hotel',
 'Eko Hotel & Suites',
 'SUNDRY CASH CUSTOMERS IBADAN',
 "EAT N'GO",
 'MRS RORO - Ijede Awo Osogbo',
 'JEMOK PETROLEUM COMPANY LTD',
 'MRS CORO - Agbor',
 'MRS Hamma Ruwa Way 2',
 'DHL INTERNATIONAL PLC',
 'SUNFLAG NIG. LTD',
 'MRS CORO - MM Highway',
 'PTML',
 'MRS CORO - Post Office',
 'MRS Maiduguri Road, Bauchi',
 'MRS CORO - Creek Road',
 'MRS CORO - Ilesha Owo ExpressWay',
 'MRS RORO - Ogunlowo Junction',
 'BUA CEMENT PLC, SOKOTO PLANT',
 'MRS RORO - Ijegun',
 'MRS MM Way Kano',
 'MRS Onipetesi',
 'MRS Adavi',
 'Celplas Industries Ltd',
 'MRS RORO - Maje Dikko Road',
 'HIFEB VENTURES',
 'SOROMAN',
 'Aina Adeyiga Shop',
 'Novo Car Rentals Plc',
 'MRS RORO - Kwata junction Awka',
 'MRS Makun',
 'MRS COCO - Maitumbi',
 'SHAVEY VENTURES LTD',
 'MRS CORO - New Market Road',
 'Holigan Global Services Ltd',
 'MRS Okene',
 'MRS RORO -Umogu Road',
 'ENL Consortium Ltd',
 'NEW BISCO',
 'MRS Aba Road',
 'MIXJET FLIGHT SUPPORT',
 'MRS RORO - Shaki',
 'Petrowest Shop',
 'MRS RORO - Tafa',
 'MRS COCO - Wharf Road',
 'OLAM NIGERIA LTD( CARAWAY FACTORY)',
 'ALKEM NIGERIA LTD',
 'Apex African Gas Nigeria Limited',
 'Marietta',
 'Eko Supreme Resources Nig. Ltd',
 'ACB ATTAH',
 'NESTOIL PLC',
 'NIGERIAN AGIP OIL COMPANY - PORT-HARCOURT',
 'Golden Transport Company',
 'A.K Haske Multi Trade Ventures',
 'MRS Garkida',
 'INTELS SERVICES LTD',
 'Bestaf Construction',
 'DAN SHAMANGE OIL & GAS LTD',
 'World Fuel Services',
 'Estandar Energy Limited',
 'General Pipes Industry Limited',
 'MRS RORO -Babs Ladipo Street',
 'MANNA BIZ VENTURES',
 'NIGERIA LIQUEFIED NATURAL GAS',
 'MRS RORO - Gashua',
 'BUA GROUP',
 'MRS RORO - Liverpool Apapa',
 'MRS COCO - Gyadi Gyadi',
 'FOLAWIYO ENERGY',
 'Relentech Specialist Nigeria Ltd',
 'EDDY BRAZIL OIL NIG',
 'MRS RORO -Mubi Byepass',
 'DE GREAT ADE DE YOUNG ENTERPRISE',
 'MRS RORO Gangarida Kachia Road',
 'The Dream Centre of the Life Oasis International Church',
 'S.B.Y General Contractors Ltd',
 'AFRICAN WIRE AND ALLIED INDUSTRIES NIG. LTD',
 'F shour Transport',
 'MRS 6th Avenue',
 'Chuniz Auto Care Nig. Ltd',
 'Vik Indutries Ltd',
 'USMAN NAGARTA OIL AND GAS',
 'MRS RORO -Abeokuta Express Road',
 'GLobal Transport Services',
 'Rom Oil Mills limited',
 'MRS COCO - Asero',
 'MRS OIL & GAS CO LTD',
 'MRS RORO -Makun Sagamu',
 'Sunti Golden Sugar Estates Limited (A division of Flourmills)',
 'RAO INVESTMENT PROPERTY COMPANY LTD',
 'Cappa and Dalberto',
 'MRS COCO - Bauchi Road',
 'TADAERIGHA',
 'Northern Nigeria Flour Mills',
 'MRS RORO - Shagamu',
 'Barhok Petroleum Ltd',
 'MRS COCO - Gwagwalada',
 'Pace Gate Ltd',
 'Premium Cassava Products Limited',
 'AVON CROWNCAPS',
 'Hull Blyth Terminals',
 'BETA GLASS COMPANY LTD - DELTA',
 'Nigerian Spinners and Dyers Ltd',
 'UAC Nigeria property Development company PLC',
 'SETRACO NIG LTD',
 'Deli foods Nigeria Limited',
 'MRS COCO - Aba Road',
 'MRS CORO - Takum',
 'Food division of UAC',
 'ONYEMOWO',
 'MRS COCO - Gaduwa',
 'DANA AIR',
 'RACK CENTRE',
 'Hayat Kimya Nigeria Ltd',
 'MRS CORO - Ilesha',
 'MRS COCO - Wulari Junction',
 'MRS COCO - Ugwu Orji',
 'PORTS & TERMINAL MULTISERVICES',
 'CHEVRON NIGERIA LTD_ LEKKI',
 'Angela Adelola Ltd',
 'MRS CORO - Ikare',
 'University Of Lagos',
 'AIR LIQUIDE NIGERIA PLC',
 'CEENOL RESOURCES NIGERIA LTD',
 'Primera Foods Nig. Ltd.',
 'CHEVRON NIGERIA LTD_WARRI',
 'PROCTER AND GAMBLE - IBADAN',
 'Full Moon Hotel Limited',
 'Great Ken-Moh Warehouse',
 'HALLIBURTON ENERGY SERVICE NIG',
 'MRS CORO - MainStreet',
 'JOY ADDAMMA CHIDI',
 'CHI Limited',
 'VITAFOAM KANO',
 'Natural Prime Resources Nig. Ltd',
 'Provast Limited',
 'RITLO INVESTMENT NIG LTD',
 'MRS Wusasa Bye-Pass',
 'A. A KARAYE MOTORS NIG LTD',
 'MRS COCO - Ahmadu Bello',
 'GRADE ONE SERVICES PRIVATE LIMITED',
 'BETA GLASS COMPANY LTD - LAGOS',
 'PZ Cussons Nigeria Plc_Ilupeju',
 'MRS RORO - Romi Kaduna',
 'ANDYMODU GLOBAL VISION LTD',
 'MRS RORO -Bunza Road',
 'MRS COCO - Agege',
 'MRS CORO - Oba Adesida Road',
 'Triple G Business Concept',
 'Aronu Motors Co. Nig Ltd (10007762)',
 'MRS RORO - Osogbo',
 'CAP PLC',
 'THE APOSTOLIC FAITH CHURCH',
 'Nur-Kareem Energy',
 'CADBURY NIGERIA PLC ONDO',
 'The Redeemed Christian Church Of God',
 'MRS RORO - Akute',
 'Edu-God Interbuiz Link',
 'PZ Cussons Nigeria Plc_Ikorodu',
 'MRS COCO - Tarauni',
 'Chemical and Allied Product PLC',
 'Mothercat Ltd',
 'GREAT VIGLADIN',
 'MRS RORO -Gakem',
 'DANA MOTORS LIMITED',
 'SAM IWUAJOKU',
 'MRS RORO - Obasanjo Street',
 'Bagco North (Division Of Flour Mills Of Nigeria PLC)',
 'Niger Mill Company Limited',
 'Y. A. Zobo Multilinks Station 1',
 'MRS COCO - South Bridge',
 'Givanas Cosmetics Nig. Ltd',
 'Business Venture',
 'DANBERTO INT. NIG',
 'MRS Oil Nigeria Plc( Internal Consumption)',
 'CADBURY NIGERIA LIMITED LAGOS',
 'MRS RORO - Suru, Kebbi',
 'Ganob Global Investment Ltd',
 'Achida Saidu Usman',
 'MRS RORO - Ajaokuta Road',
 'MRS Isolo',
 'Japaul Oil And Maritime Services Plc',
 "EKEPEX GLOBAL INT'L LTD",
 'MRS RORO - Malumfashi',
 'N. Emiloju I.C. Ltd',
 'MRS RORO -Numan',
 'Brass & Dome Limited Station 1',
 'NIGERIAN EAGLE FLOUR MILLS (FLOUR MILLS)',
 'Camosa Project Ltd',
 'Ustaf Global',
 'Chuken Global Services',
 'MRS RORO -Kamba-Dandi',
 'A. S. PAJA OIL AND GAS NIGERIA',
 'HOLTON CROFT INTERNATIONAL',
 'Egypt Air',
 'MRS RORO - New Road, Adaka_',
 'MRS CORO - Okpara Avenue',
 'Muchez Pramark Enterprises',
 'Aluminium Rolling Mills, Ota',
 'MRS Kumbotso',
 'AG Leventis',
 'Arik Air Limited_10008995',
 'MRS Azare Shop',
 'Depasa Marine International Nig. Ltd',
 'Lekki Free Zone Development Company',
 'Global Star Energy Services',
 'MRS Mbube Road',
 'SIFAX Group of Companies Limited',
 'Adler Shop',
 'MRS KM 22, Zaria Road',
 'MRS Keffi',
 'MRS Numan Road Jimeta',
 'Honeywell Flour Mills PLC',
 'Animex Industries Nigeria Limited',
 'MRS RORO - Nguru Road',
 'MRS RORO -Numan Road Jimeta',
 'IBB Oil and Gas',
 'MRS RORO -Zaria Road',
 'MRS RORO - Makun Sagamu',
 'Premium Edible Oil Products Limited',
 'CITA BULK STORAGE FACILITIES LIMITED',
 'MRS South Bridge Kaduna',
 'GOGO ALLIED IMPEX AND SERVICES LIMITED',
 'MRS Fanisua',
 'Premier Feed Mills',
 'Sai Allah Investment & Haulage Co. Ltd',
 'ETHICAL AUTODYNAMICS LTD',
 'AYM SHAFA WAREHOUSE',
 'MRS RORO - Itamope',
 'MRS RORO - Oron Road',
 'MRS RORO -Idiroko Road',
 'MRS RORO -Amawbia',
 'MRS RORO -Isolo',
 'MRS RORO - Amuloko',
 'MRS RORO -Fola Agoro',
 'MRS RORO - Oja Bus-Stop',
 'Hudson Pacific Energy Limited',
 'CHAMPIONS BREWERIES',
 'Havilah Energy & Logistics Limited',
 'MRS COCO - Ekewan Road',
 'MRS RORO -Ado Ota',
 'Azikel Group',
 'MRS RORO - Mbalana Numan',
 'K K International',
 'NORSKY GLOBAL',
 'QUITS AVIATION SERVICES FZE',
 'Ok Foods Ltd (OLAM)',
 'Pipeline & Product Marketing Company',
 'Nigerian Navy',
 'MRS CORO - Asa Road Jubilee Junction',
 'Makeem Global Resources. Station 1',
 "CHUMAC INT'L MACHINARIES",
 'MRS CORO - Ugwu Orji',
 'Milaco & Associate (Nig) Ltd Station 1',
 '3LC Innovate Energy Ltd',
 'Kakaraka Industries Limited',
 'SARCO PETROLEUM & GAS LTD',
 'COWERIE GLOBAL COMPANY LIMITED',
 'A. A. ADAMCY & SONS NIG LTD Station 1',
 'MRS CORO - Southbrige',
 'MRS CORO - Tarauni',
 'MRS CORO - Unijos',
 'Chellarams PLC',
 'MRS RORO - Maiduguri Road Gashua',
 'A. A. SALISU AND SONS NIGERIA LIMITED',
 'MRS CORO - Gwagwalada',
 'Zoom Energie Row Limited',
 'KATARTIZO INVESTMENT SERVICES LTD',
 'Masid Multi Purpose Services Ltd',
 'MRS CORO - Samaru',
 'KAMJAZA VENTURES LIMITED 1',
 'DIWAGIO LTD',
 'Perth Energy Limited',
 'MRS Otukpo',
 'SUPERMARINE SERVICES LIMITED',
 'PENTAGON SECURITIES LTD',
 'FLYBIRD AVIATION SUPPORT LTD',
 'EMIRATE TOUCH AVIATION SERVICES LTD',
 'IC DERAS ENERGY LIMITED',
 'M J MULTIPURPOSE SERVICES LIMITED Station 1',
 'EDUS CONCERN',
 'ASAF OIL COMPANY NIGERIA LIMITED Station 1',
 'UMEH UCHE MARTIN & SONS (NIG) LTD. Station 1',
 'Chris-Ton Global Agency Limited',
 'ORION MARINE LIMITED',
 'MRS RORO- Numan Road 2',
 'Otunba Joju Olanrewaju',
 'B.O GAS AND CHEMICAL LIMITED Station 1',
 'PATRON F.I. BUILDERS Station 1',
 'MRS CORO - Brazillian Quarters',
 'MRS CORO - Wharf Road Apapa',
 'JESSONIC OIL & GAS VENTURES',
 'TEGVAD ENGINEERING AND PETROCHEMICAL LTD',
 'MRS CORO AGEGE ROAD',
 'MRS CORO - Rumuomasi',
 'B.O GAS AND CHEMICAL LIMITED',
 'MRS CORO Brazillian Quarters',
 'MRS CORO - Mokola',
 'MRS CORO Onipetesi',
 'Milaco & Associate (Nig) Ltd',
 'Launi Trading Investment',
 'Y. A. Zobo Multilinks',
 'MRS RORO - Numan Road Jimeta',
 'MRS CORO Bauchi Road',
 'MRS RORO - Bypass Road Suru',
 'MRS RORO - Gaya Road',
 'MRS CORO Southbrige',
 'MRS RORO - Fanisua',
 'MRS RORO - Old Ife Road',
 'MRS CORO Samaru',
 'MRS RORO - Omobolanle, Osogbo',
 'MRS RORO - Port Harcourt Road Aba',
 'MRS RORO - Ikire (II)',
 'MRS CORO Asa Road Jubilee Junction',
 'MRS CORO Ekewan Road',
 'MRS RORO - Oron',
 'MRS CORO Mission Road',
 'MRS RORO - Gakem',
 'MRS CORO Rumuomasi',
 'MRS RORO - 6th Avenue',
 'MRS RORO - Mubi Road Michika',
 "MRS COCO Emir's Market",
 'FEDICO MOTORS ENTERPRISES',
 'MRS RORO - Sokoto Byepass',
 'MRS RORO - Garkida',
 'MRS CORO Uwani',
 'MRS CORO Emene',
 'MRS RORO - Fola Agoro',
 'MRS COCO - Ahmadu Bello Otukpo',
 'MRS RORO - Dakingari',
 'MRS RORO - Adogo',
 'Dangote Cement PLC (Transport Division)',
 'MRS RORO - Yandev Gboko Road',
 'MRS CORO Agege Road',
 'MRS CORO - Mbube Road',
 'MNE TRANSPORTATION AND LOGISTICS Station 1',
 'CROWN FLOUR MILLS LTD',
 'TB GEM AND MATE LIMITED',
 'MRS CORO Ugwu Orji',
 "House of Five A's Nigeria Limited",
 'A.A JAMTARI OIL NIG. LTD',
 'VIVI GOLD VENTURES',
 'MRS RORO - Maiduguri Road Tudan Wade',
 'BARKA MATATA VENTURES LTD',
 'ALLERPLUS RESOURCES LIMITED',
 'MRS RORO - Ogo Oluwa Gbogan',
 'MRS RORO - Obudu',
 'HONOZ INTEGRATED SERVICES',
 'DIAPER',
 'MRS RORO - Sabongari Area Bunza',
 'DUNAC INVESTMENT LIMITED',
 'MRS RORO - Ikate Lekki',
 'MRS CORO Ali Akilu Road',
 'MRS RORO - Kaduna Road Keffi',
 'CF-ONYI EZEMA ENTERPRISES',
 'MRS CORO Wudil ByePass Tarauni',
 'LIZSUN PETROLEUM SERVICES LIMITED',
 'SEWALE NIGERIA LIMITED',
 'MRS RORO - Old Ojo Road',
 'MRS CORO Cityway',
 'MRS CORO Itire Road Lawanson',
 'E C AKUDO GLOBAL CONCEPT LTD',
 'ALHABAF NIG LTD',
 'ABANIK OIL & GAS LTD.',
 'MOS Energy Company Ltd',
 'MRS CORO Terminus',
 'MRS CORO Isolo Road Oke Afa',
 'MATT-CLIEF VENTURES LIMITED',
 'MRS COOPERATIVE',
 'MEGA CHICKEN RESTAURANT LIMITED',
 'MAYFLAME NIG. LTD',
 'UNITED NIGERIA AIRLINE COMPANY LIMITED',
 'SKYJET AVIATION SERVICES LTD',
 'GOLD SKIES AIR LIMITED',
 'Overland Airways Ltd',
 'Allied Air Limited',
 'SUMTECH CONSULTANTS LIMITED',
 'MRS RORO - Ojodu-Berger',
 'MRS RORO - Aboru Road',
 'B O Gas and Chemical LTD Badagry',
 'B O Gas and Chemical LTD Oke Ora',
 'MRS COCO Ebute Meta',
 'Lado Oil & Chemical Limited Otta Road',
 'MRS RORO - Warewa',
 'MRS COCO - Alapere',
 'Vinny Star Continental Merchandise Station 1',
 'B O Gas and Chemical LTD Ibesa',
 'A. A. JAMARI & SONS NIG LTD',
 'Lado Oil and Chemical Ijede Road',
 'Eddyfab International Nigeria Ltd Station 1',
 'EZEOBI-VAL SYSTEMS LIMITED',
 'COCO Alapere Fuel dump',
 'B O Gas and Chemical LTD Ikirun Road',
 'IBOM AIRLINE LTD',
 'Global Bulk Fuels Ltd',
 'NSO Automechanic Station 1',
 'Lateshy Resources Nigeria Limited Station 1',
 'SANAB GLOBAL RESOURCES Station 1',
 'McLuxury Roof Station 1',
 'Joe Kate Enterprises Station 1',
 'Lado Oil and Chemical Egbe Town',
 'RAPID ADVANCED CONCEPT LIMITED Station 1',
 'SAMYTEX & SONS ENTERPRISE Station 1',
 'DE BRIGHT GLOBAL OSOTEX LTD Station 1',
 'V-TIME MARINE SERVICES NIGERIA LIMITED Station 1',
 'AMINUTECH AUTO WORLDWIDE Station 1',
 'MRS RORO- Kofare Road',
 'A. A. ADAMCY & SONS NIG LTD',
 'AMAGWU INDUSTRIAL VENTURES LTD Station 1',
 'A.O CHIDI UNIQUE VENTURES LTD',
 'MRS Transport Company (Bestaf)',
 'A.H. LABARAN NIG. LTD',
 'PERHOO INTEGRATED RESOURCES LIMITED Station 1',
 'BASH INTERNATIONAL LUBRICANT OIL',
 'MRS CORO Ogoja',
 'KEROJET SERVICES LIMITED',
 'HI-GRADE CONTEMPORARY',
 'SAF PETROLEUM',
 'Jeinpac Integrated Services Ltd',
 'AFRAB CHEM LTD',
 'Omowealth Nig. Ltd',
 'Kasha Nigeria Ltd',
 'Ochemic Energy',
 'Energymatics Ltd',
 'MRS RORO - Mararaba Road, Mubi',
 'Chamahl March Company Ltd Station 1',
 'Rainbow.O',
 'Sabotoys Toye Resources Station 1',
 'MRS CORO BERNARD CARR STREET',
 'MRS CORO OGOJA',
 'Paddy- E Multi-Concept Enterprises Station 1',
 'Onbass Investment Ltd Station 1',
 'OMONIYI OLA0OLUWA AND SONS LIMITED Station 1',
 'MRS Transport Company Limited',
 'Mishfat Oil &Gas Limited Station 1',
 'SHIRASH- NAPRI GATE',
 'SHIRASH-HAUWA BRIDGE STATION',
 'MRS RORO - Kalanko NTA ByePass Jalingo',
 'SHIRASH-KWAMBA,SULEJA',
 'SHIRASH-SAKI',
 'MRS RORO - Biyu Road Mararaban Mayo Raneyo',
 'A.H Labaran Nigeria Limited',
 'QUITS AVIATION FREE ZONE COMPANY',
 'MRS RORO - MAUTECH Sangere',
 'Greataf Trading Company Limited',
 'MRS RORO Ijoko Sango B. O. Gas',
 'Sinopec Oil & Gas Service Nigeria Limited',
 'MRS COCO Airport Road, Abuja',
 'MRS RORO - Badagry',
 'Bestaf Trading Co. Ltd',
 'ASAF OIL COMPANY NIGERIA LIMITED',
 'MRS CORO WHARF ROAD APAPA',
 'GUZONTAL ENTERPRISES',
 'MRS RORO Wukari Road Yerima',
 'Polam Nig Ltd Station 1',
 'MRS RORO Ile Igbon',
 'MRS LPG Alapata',
 'Chief Awaco Nig. Ltd Station 1',
 'MRS CORO-OTUKPO']




from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity


# Create the TF-IDF vectorizer
vectorizer = TfidfVectorizer()

# Fit and transform the company names into TF-IDF vectors
tfidf_vectors = vectorizer.fit_transform(company_names)

def get_highest_match(query):
    # Transform the query into a TF-IDF vector
    query_vector = vectorizer.transform([query])

    # Calculate the cosine similarity between the query vector and the company name vectors
    similarity_scores = cosine_similarity(query_vector, tfidf_vectors)[0]

    # Find the index of the highest similarity score
    highest_index = similarity_scores.argmax()

    # Retrieve the highest similarity score
    highest_score = similarity_scores[highest_index]

    # Retrieve the company name with the highest score
    company_name = company_names[highest_index]

    return highest_score, company_name

# Example usage
query = 'What is the revenue of this Comapny MRS roro mautexh sangere'

highest_score, matched_company = get_highest_match(query)
print("Highest Match Score:", highest_score)
print("Matched Company Name:", matched_company)


# from sklearn.feature_extraction.text import TfidfVectorizer
# from sklearn.metrics.pairwise import cosine_similarity
# from sklearn.pipeline import Pipeline
# from sklearn.ensemble import RandomForestClassifier
# from sklearn.model_selection import train_test_split
# import nltk
# from nltk.corpus import stopwords
# from nltk.tokenize import word_tokenize
# from nltk.stem import WordNetLemmatizer
#
#
# nltk.download('stopwords')
# nltk.download('punkt')
# nltk.download('wordnet')
#
# stop_words = set(stopwords.words('english'))
# lemmatizer = WordNetLemmatizer()
#
# def preprocess_text(text):
#     # Tokenize the text
#     tokens = word_tokenize(text)
#
#     # Remove punctuation and convert to lowercase
#     tokens = [token.lower() for token in tokens if token.isalnum()]
#
#     # Remove stop words
#     tokens = [token for token in tokens if token not in stop_words]
#
#     # Lemmatize tokens
#     tokens = [lemmatizer.lemmatize(token) for token in tokens]
#
#     # Join tokens back into a single string
#     processed_text = ' '.join(tokens)
#
#     return processed_text
#
# # Data preparation
#
# queries = [
#     'What is the revenue of this Comapny MRS mautexh sangere'
# ]
#
# # Preprocess company names and queries
# processed_company_names = [preprocess_text(name) for name in company_names]
# processed_queries = [preprocess_text(query) for query in queries]
#
# # Create TF-IDF vectorizer and Random Forest classifier pipeline
# pipeline = Pipeline([
#     ('tfidf', TfidfVectorizer()),
#     ('clf', RandomForestClassifier(n_estimators=100))
# ])
#
# # Split data into train and test sets
# X_train, X_test, y_train, y_test = train_test_split(processed_company_names, range(len(processed_company_names)), test_size=0.2, random_state=42)
#
# # Train the model
# pipeline.fit(X_train, y_train)
#
# # Evaluate the model
# accuracy = pipeline.score(X_test, y_test)
# # print("Accuracy:", accuracy)
#
# # Predict matches for queries
# predicted_matches = pipeline.predict(processed_queries)
#
# # Print predicted matches
# for query, match_index in zip(queries, predicted_matches):
#     print("Query:", query)
#     print("Matched Company Name:", company_names[match_index])











